modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="all_gems_items"
version="1.0.0"
displayName="all gems items"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="HP, MCreator"

[[dependencies.all_gems_items]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




